node-repo: fix getBotPrLabels
Fixes the following error occurring in production, likely happening due
to the recent bump in dependencies.

```
10:49:01.780 FATAL bot: Unchaught exception, terminating bot process immediately
    TypeError: events[Symbol.iterator] is not a function
        at githubClient.issues.getEvents (/home/iojs/github-bot/lib/node-repo.js:163:23)
        at /home/iojs/github-bot/node_modules/github/lib/index.js:912:9
        at callCallback (/home/iojs/github-bot/node_modules/github/lib/index.js:738:9)
        at IncomingMessage.<anonymous> (/home/iojs/github-bot/node_modules/github/lib/index.js:810:13)
        at emitNone (events.js:91:20)
        at IncomingMessage.emit (events.js:185:7)
        at endReadableNT (_stream_readable.js:978:12)
        at _combinedTickCallback (internal/process/next_tick.js:80:11)
        at process._tickCallback (internal/process/next_tick.js:104:9)
```

Refs: https://github.com/nodejs/github-bot/pull/188