jenkins: parse PR number into a number while extracting from git ref
Primarily done because the GraphQL client validation done when fetching
existing bot comments, exploded because an invalid `Int!` value was
provided:

```
00:42:03.038Z ERROR bot: Error while creating comment on GitHub (req_id=baae5340-8be1-11e9-a4d0-856e0a231c31)
    GraphqlError: Variable number of type Int! was provided invalid value
        at request.then.response (/home/../node_modules/@octokit/graphql/lib/graphql.js:31:15)
```

Doing an explicit `string -> number` convertion when extracting the
PR number from the related git ref hopefully fixes this error, since it
*should* be a valid `Int!` now.